### ISSUE TITLE
Улучшеное оформление README.md

### ISSUE THREAD

**Issue by lomraig** [AlexRazor1337/JAM#8]
Я предлаю оформить так:

Installation

All libraries except two(gtk3 and json-c) are included with source code. gtk3 and json-c must be installed separately:
Ubuntu:
apt-get install libgtk-3-dev json-c
Arch Linux:
pacman -S gtk3 json-c
Fedora:
dnf install gtk3 json-c

When everything is installed just call make.

**Comment by AlexRazor1337** [comment]
@Savolus так же можно исправить имя пакета json-c в apt-get
